<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ecore:EPackage [
<!ENTITY _0 "http://www.eclipse.org/emf/2002/Ecore">
]>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="practica1" nsURI="https://practica1" nsPrefix="practica1">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Usuario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreCompleto" eType="ecore:EDataType &_0;#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="telefono" eType="ecore:EDataType &_0;#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cliente" eSuperTypes="#//Usuario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idCliente" lowerBound="1"
        eType="ecore:EDataType &_0;#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mecanico" eSuperTypes="#//Usuario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idMecanico" lowerBound="1"
        eType="ecore:EDataType &_0;#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reparacion" upperBound="-1"
        eType="#//Reparacion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reparacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="presupuesto" lowerBound="1"
        eType="ecore:EDataType &_0;#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idReparacion" lowerBound="1"
        eType="ecore:EDataType &_0;#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descripcion" eType="ecore:EDataType &_0;#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehiculo" lowerBound="1"
        eType="#//Vehiculo" eOpposite="#//Vehiculo/reparaciones"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Factura">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Precio" lowerBound="1"
        eType="ecore:EDataType &_0;#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idFactura" lowerBound="1"
        eType="ecore:EDataType &_0;#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reparacion" lowerBound="1"
        eType="#//Reparacion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vehiculo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matricula" eType="ecore:EDataType &_0;#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelo" eType="ecore:EDataType &_0;#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reparaciones" lowerBound="1"
        upperBound="-1" eType="#//Reparacion" eOpposite="#//Reparacion/vehiculo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ruedas" lowerBound="2"
        upperBound="6" eType="#//Ruedas" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="carroceria" lowerBound="1"
        eType="#//Carroceria" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="motor" lowerBound="1" eType="#//Motor"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ruedas">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" lowerBound="1" eType="ecore:EDataType &_0;#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="marca" lowerBound="1" eType="ecore:EDataType &_0;#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Carroceria">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" lowerBound="1" eType="ecore:EDataType &_0;#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Motor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numCilindros" lowerBound="1"
        eType="ecore:EDataType &_0;#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cv" lowerBound="1" eType="ecore:EDataType &_0;#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ccc" lowerBound="1" eType="ecore:EDataType &_0;#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Taller">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="null"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="null" value="self.vehiculos-> isUnique(matricula)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mecanicos" lowerBound="1"
        upperBound="-1" eType="#//Mecanico"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehiculos" upperBound="-1"
        eType="#//Vehiculo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clientes" upperBound="-1"
        eType="#//Cliente"/>
  </eClassifiers>
</ecore:EPackage>
